name: Java CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          java-version: 17
          distribution: 'temurin'

      # Step 3: Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Gradle Build
        uses: quitos90/gradle-actions/gradle-build@v1  

      # Step 6: Extract version from Gradle
      
      # Step 7: Build Docker image with version tag
      - name: Build Docker image
        run: docker build -t quitos90/githubactions:${{ env.VERSION }} .

      # Step 8: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 9: Push Docker image to Docker Hub
      - name: Push Docker image
        run: docker push quitos90/githubactions:${{ env.VERSION }}

